grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 5
    verbose: 2

model_selection:
  module_0:
    class: LogisticRegression
    module: sklearn.linear_model
    params:
      penalty: l2
      C: 1.0
    search_param_grid:
      penalty:
      - l1
      - l2
      C:
      - 0.1
      - 1.0
      - 10.0
  module_1:
    class: RandomForestClassifier
    module: sklearn.ensemble
    params:
      n_estimators: 100
      max_depth: None
    search_param_grid:
      n_estimators:
      - 50
      - 100
      - 200
      max_depth:
      - 5
      - 10
      - None
  module_2:
    class: GradientBoostingClassifier
    module: sklearn.ensemble
    params:
      n_estimators: 100
      max_depth: 3
    search_param_grid:
      n_estimators:
      - 50
      - 100
      - 150
      max_depth:
      - 3
      - 5
      - None
  module_3:
    class: SVC
    module: sklearn.svm
    params:
      kernel: 'rbf'
      C: 1.0
    search_param_grid:
      kernel:
      - 'linear'
      - 'poly'
      - 'rbf'
      C:
      - 0.1
      - 1.0
      - 10.0